services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Asia/Dhaka
    volumes:
      - ${ROOT_PATH}/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Asia/Dhaka
    volumes:
      - ${ROOT_PATH}/radarr/config:/config
      - ${MOVIES_LOCATION}:/movies
      - ${BITTORRENT_LOCATION}:/downloads
      - ${BITTORRENT_LOCATION}:/Downloads # Needed to suppress the "/Downloads" folder error
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Asia/Dhaka
    volumes:
      - ${ROOT_PATH}/sonarr/config:/config
      - ${SERIES_LOCATION}:/tv
      - ${ANIME_LOCATION}:/anime
      - ${BITTORRENT_LOCATION}:/downloads
      - ${BITTORRENT_LOCATION}:/Downloads # Needed to suppress the "/Downloads" folder error
    ports:
      - 8989:8989
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Asia/Dhaka
    volumes:
      - ${ROOT_PATH}/bazarr/config:/config
      - ${SERIES_LOCATION}:/tv
      - ${MOVIES_LOCATION}:/movies
    ports:
      - 6767:6767
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=info
      - TZ=Asia/Dhaka
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - /jellyseerr/config:/app/config
    restart: unless-stopped
