services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Dhaka
    volumes:
      - ${ROOT_PATH}/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Dhaka
    volumes:
      - ${ROOT_PATH}/radarr/config:/config
      - ${MOVIES_LOCATION}:/movies
      - ${BITTORRENT_LOCATION}:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Dhaka
    volumes:
      - ${ROOT_PATH}/sonarr/config:/config
      - ${SERIES_LOCATION}:/tv
      - ${BITTORRENT_LOCATION}:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Dhaka
    volumes:
      - ${ROOT_PATH}/bazarr/config:/config
      - ${SERIES_LOCATION}:/tv
      - ${MOVIES_LOCATION}:/movies
    ports:
      - 6767:6767
    restart: unless-stopped
