version: 0.14

tls:
  enabled: false

mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

record:
  enabled: true
  retain:
    days: 7

detect:
  enabled: false

detectors:
  cpu1:
    type: cpu
    num_threads: 3
  cpu2:
    type: cpu
    num_threads: 3

cameras:
  garage:
    enabled: true
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://dijkstra:VeryStrongPassword@0@192.168.68.108:554/stream1
          roles:
            - record
        # Low Resolution Stream
        - path: rtsp://dijkstra:VeryStrongPassword@0@192.168.68.108:554/stream2
          roles:
            - detect
    onvif:
      host: http://192.168.68.108:2020/onvif/device_service
      user: "dijkstra"
      password: "VeryStrongPassword@0"
  
  stair:
    enabled: true
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://dijkstra:VeryStrongPassword@0@192.168.68.104:554/stream1
          roles:
            - record
        # Low Resolution Stream
        - path: rtsp://dijkstra:VeryStrongPassword@0@192.168.68.104:554/stream2
          roles:
            - detect
    onvif:
      host: http://192.168.68.104:2020/onvif/device_service
      user: "dijkstra"
      password: "VeryStrongPassword@0"

  front-road:
    enabled: true
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://dijkstra:VeryStrongPassword@0@192.168.68.125:554/stream1
          roles:
            - record
        # Low Resolution Stream
        - path: rtsp://dijkstra:VeryStrongPassword@0@192.168.68.125:554/stream2
          roles:
            - detect

  backside:
    enabled: true
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://dijkstra:VeryStrongPassword@0@192.168.68.124:554/stream1
          roles:
            - record
        # Low Resolution Stream
        - path: rtsp://dijkstra:VeryStrongPassword@0@192.168.68.124:554/stream2
          roles:
            - detect

