services:
  uptime-kuma:
    image: ghcr.io/louislam/uptime-kuma
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "4000:3001"
    volumes:
      - ${DATA_LOCATION}:/app/data