services:
  convertx: 
    image: ghcr.io/c4illin/convertx
    container_name: convertx
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - JWT_SECRET=${JWT_SECRET} # will use randomUUID() if unset
    volumes:
      - ${DATA_LOCATION}:/app/data