services:
  convertx: 
    image: ghcr.io/c4illin/convertx
    container_name: convertx
    restart: unless-stopped
    ports:
      - 3005:3000
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - HTTP_ALLOWED=true
    volumes:
      - ${DATA_LOCATION}:/app/data